[package]
name = "taquin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
generic-matrix = "0.2.2"
matrix = "0.22.0"
rand = "0.8.5"
nalgebra="0.21.0"
